### ISSUE TITLE
Add LORE section / page

### ISSUE THREAD

**Issue by bountyx** [shroomies-nft/shroomies.xyz#12]

**Comment by bountyx** [comment]
Duplicate 'Interactive+AR' section and place above team section, @nighthoch will add copy and images

**Comment by nighthoch** [comment]
shroomies.xyz/main/assets/img/lore.png

**Comment by nighthoch** [comment]
Title : Shroomies Lore

Body Text: Shroomies are a lifeform discovered on a small unmarked island in the Northern Pacific ocean. Among them pockets of an unknown glowing blue goo-like substance was also discovered that appears to affect organic matter in very strange alien ways. This blue goo should be considered dangerous and extreme caution used if found.
